//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalAsistencia
{
    public partial class HistorialRechazosJefe
    {
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        protected global::System.Web.UI.WebControls.GridView gvHistorial;
    }
}
